#!/bin/bash

OUT=$(xrandr | grep " connected" | cut -f1 -d " " | dmenu -i  -p "Select video output")

BRIGHTNESS=$(printf "0.1\n0.3\n0.6\n0.9\n1\n" | dmenu  -p "Select brightness level")

xrandr --output $OUT --brightness $BRIGHTNESS
