#!/bin/bash

SINK=$(pactl list sinks | grep Name | awk '{ print $2 }' | dmenu -p "Which Sink?")

VOLUME=$( printf "0\n30\n50\n80\n100\n" | dmenu -p "Select volume")

pactl set-sink-volume $SINK $VOLUME%

